install.packages("ggplot2")
data(diamonds)
require(ggplot2)
head(diamonds)
tail(diamonds)
aggregate(price~cut,diamonds,mean)
aggregate(price~cut+color,diamonds,mean,na.rm=TRUE)
aggregate(price~cut+color,diamonds,mean)
aggregate(cbind(price,carat)~cut,diamonds,mean)
aggregate(cbind(price,carat)~cut+color,diamonds,mean)

install.packages("plyr")
require(plyr)
data(baseball)
head(baseball)
tail(baseball)
baseball$sf[baseball$year<1954]<-0
any(is.na(baseball$sf))
baseball$hbp[is.na(baseball$hbp)]<-0
any(is.na(baseball$hbp))
baseball<-baseball[baseball$ab>=50,]
baseball$OBP<-with(baseball,(h+bb+hbp)/(ab+bb+hbp+sf))
tail(baseball)